### ISSUE TITLE
Restyling: Renewal of the Checkout Pages

### ISSUE THREAD

**Issue by msaroshali** [Xceptance/posters-demo-store#29]
**Tasks**

- [x] Add process Indicator
- [x] Restyle Guest Shipping Address page
- [x] Restyle Guest Billing Address page
- [x]  Restyle Guest Payment Detail page
- [x] Restyle Order Overview Page
- [x] Restyle Billing Address page
- [x] Restyle Payment Detail page
- [x] Restyle Checkout Header
