### ISSUE TITLE
Backoffice: Sidebar

### ISSUE THREAD

**Issue by Kenspectacle** [Xceptance/posters-demo-store#71]
## Motivation

makes traveling between pages easier

## Todo:

- [x] fix Dashboard link
- [x] add Users list hotlink 
- [x] add Orders list hotlink
- [x] add Customers list hotlink
- [x] preferences
- [x] import/export
- [x] Keep users options
- [x] Did a small styling
- [x] added Webshop as a drop-menu
