### ISSUE TITLE
Backoffice: Finish Customers Implementation

### ISSUE THREAD

**Issue by Kenspectacle** [Xceptance/posters-demo-store#83]
## Motivation

Fully functional orders pages for the back office based on business requirement

## Todo:

- [x] Make the Customers listing
- [x] Implement the customer's viewport
- [x] Implement the customer's edit function
