### ISSUE TITLE
Backoffice: Finish Products Implementation

### ISSUE THREAD

**Issue by Kenspectacle** [Xceptance/posters-demo-store#85]
## Motivation

Fully functional products pages for the back office based on business requirement

## Todo:

- [x] Make the products listing
- [x] Implement the product's viewport
- [x] Implement the product's edit function
