### ISSUE TITLE
Backoffice: Viewing list remove list style and style it to the left

### ISSUE THREAD

**Issue by Kenspectacle** [Xceptance/posters-demo-store#87]
makes it more appealing visually

## Todo

- [x] Create style
- [x] Apply to Product View
- [x] Apply to Customer View
- [x] Apply to User view
- [x] Apply to Order view
